/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_bunnyblue_droidncm_dump_NcmDumper */

#ifndef _Included_io_bunnyblue_droidncm_dump_NcmDumper
#define _Included_io_bunnyblue_droidncm_dump_NcmDumper
#include <android/log.h>

#define  LOG_TAG    "droidNCM"

#define  LOGE(...)  __android_log_print(ANDROID_LOG_ERROR,LOG_TAG,__VA_ARGS__)
#define  LOGW(...)  __android_log_print(ANDROID_LOG_WARN,LOG_TAG,__VA_ARGS__)
#define  LOGD(...)  __android_log_print(ANDROID_LOG_DEBUG,LOG_TAG,__VA_ARGS__)
#define  LOGI(...)  __android_log_print(ANDROID_LOG_INFO,LOG_TAG,__VA_ARGS__)

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_bunnyblue_droidncm_dump_NcmDumper
 * Method:    ncpDump
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_bunnyblue_droidncm_dump_NcmDumper_ncpDump
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
